### ISSUE TITLE
Allow broadcast from outside of the Group

### ISSUE THREAD

**Issue by mikecann** [cloudflare/dog#13]
I have a usecase where I want to beble to broadcast a message from outside of the Replica.

Suppose I have a worker with a REST endpoint that needs to broadcast a message to all the connected sockets. There is currently no way of doing as far as I can tell, is that right?

Edit: Actually I guess I could override the "fetch" method in my extension of Group (Lobby) and handle it there, tho the docs does say `@NOTE: User should NOT redeclare/override this method.`

Edit: Actually no this wont work as the [mapping and kids](https://github.com/cloudflare/dog/blob/master/src/group.ts#L18) are privates and thus not accessible from the child Group. The Group / Lobby needs a broadcast method itself I think.

**Comment by codewithkristian** [comment]
cc @lukeed

**Comment by lukeed** [comment]
There are now HTTP-exposed `emit`, `broadcast`, and `whisper` methods. You can access them from within the your `Replica`-extension's `receive` method.

While this doesn't _directly_ satisfy the issue's title ("from outside of the Group"), this is the best/ideal to achieve this behavior. Your HTTP routing logic controls what happens & when, and is responsible for filtering requests to an eventual `this.broadcast({ ... })` call somewhere in your class. You can see the example code within the linked commit.

Hope that helps~!

**Comment by mikecann** [comment]
Awesome @lukeed this is fantastic thanks mate :)
