### ISSUE TITLE
Problems with the example

### ISSUE THREAD

**Issue by mikecann** [cloudflare/dog#9]
1. The example readme.md tells you to replace the dependency in the package.json to ` "dog": "next"` unfortunately doing this causes compile errors because the `next` version is not compatible

2. Attempting `wrangler publish` from the examples package errors with: 

![image](https://user-images.githubusercontent.com/215033/146486785-58eb636b-5253-4f36-b376-be1f438c44ca.png)

**Comment by mikecann** [comment]
nevermind, I think this too was user error

**Comment by rizkyramadhan** [comment]
Hey, this happens to me too. What did you do ?

**Comment by lukeed** [comment]
Use the latest version now as dog has now been published. I’ll update the readme
